export namespace HFontConstants {

  export const SIZE_18 = "18"

  export const SIZE_16 = "16"

  export const SIZE_15 = "15"

  export const SIZE_14 = "14"

  export const SIZE_13 = "13"

  export const SIZE_12 = "12"

  export const SIZE_10 = "10"

  export const COLOR_CT_1 = $r("app.color.ct_1")

  export const COLOR_CT_2 = $r("app.color.ct_2")

  export const COLOR_CT_3 = $r("app.color.ct_3")
}