export namespace HUIConstants {

  export const FULL_PERCENT = "100%"

  export const AUTO = "auto"

  export const ZERO = "0"


  export const HEIGHT_BAR = "44"

  export const HEIGHT_LINE = "0.5"


  export const PADDING_6 = "6"

  export const PADDING_8 = "8"

  export const PADDING_10 = "10"

  export const PADDING_12 = "12"

  export const PADDING_14 = "14"

  export const PADDING_20 = "20"

  export const PADDING_40 = "40"


  export const COLOR_LINE = $r("app.color.color_line")

  export const COLOR_ALERT = $r("app.color.color_alert")
}